FROM wazoplatform/wazo-base-db
LABEL maintainer="Wazo Maintainers <dev@wazo.community>"

COPY . /usr/src/wazo-provd
WORKDIR /usr/src/wazo-provd
ENV ALEMBIC_DB_URI postgresql://wazo-provd:Secr7t@localhost/wazo-provd

RUN true \
    && python3 setup.py install \
    && pg_start \
    && wazo-provd-init-db --user postgres --pg_db_uri postgresql:///postgres --provd_db_uri postgresql:///wazo-provd --db wazo-provd --owner wazo-provd --password Secr7t \
    && (cd /usr/src/wazo-provd && python3 -m alembic.config -c provd/database/alembic.ini upgrade head) \
    && pg_stop \
    && true
USER postgres
